<<<<<<< HEAD
const arrPokemons = [
    {
        image: "url('../image/psyduck.png')",
        name: 'Псайдак',
        health: 100,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        image: "url('../image/bulbasaur.png')",
        name: 'Бульбазавр',
        health: 150,
        hunger: 150,
        hygiene: 150,
        depression: 150,
    },
    {
        image: "url('../image/charmander.png')",
        name: 'Чармандер',
        health: 160,
        hunger: 140,
        hygiene: 120,
        depression: 110,
    },
    {
        image: "url('../image/squirtle.png')",
        name: 'Сквиртл',
        health: 140,
        hunger: 130,
        hygiene: 100,
        depression: 120,
    },
    {
        image: "url('../image/bellsprout.png')",
        name: 'Беллспраут',
        health: 180,
        hunger: 160,
        hygiene: 140,
        depression: 110,
    },
    {
        image: "url('../image/meowth.png')",
        name: 'Мяут',
        health: 150,
        hunger: 170,
        hygiene: 100,
        depression: 100,
    },
    {
        image: "url('../image/pidgeotto.png')",
        name: 'Пиджеотто',
        health: 200,
        hunger: 200,
        hygiene: 200,
        depression: 200,
    },
    {
        image: "url('../image/pikachu.png')",
        name: 'Пикачу',
        health: 250,
        hunger: 250,
        hygiene: 250,
        depression: 250,
    },
    {
        image: "url('../image/sandshrew.png')",
        name: 'Сэндшрю',
        health: 150,
        hunger: 160,
        hygiene: 180,
        depression: 190,
    },
    {
        image: "url('../image/slowpoke.png')",
        name: 'Слоупок',
        health: 300,
        hunger: 300,
        hygiene: 300,
        depression: 300,
    },
=======
const arrPokemons = [
    {
        image: "url('../image/psyduck.png')",
        name: 'Псайдак',
        health: 100,
        hunger: 100,
        hygiene: 100,
        depression: 100,
    },
    {
        image: "url('../image/bulbasaur.png')",
        name: 'Бульбазавр',
        health: 150,
        hunger: 150,
        hygiene: 150,
        depression: 150,
    },
    {
        image: "url('../image/charmander.png')",
        name: 'Чармандер',
        health: 160,
        hunger: 140,
        hygiene: 120,
        depression: 110,
    },
    {
        image: "url('../image/squirtle.png')",
        name: 'Сквиртл',
        health: 140,
        hunger: 130,
        hygiene: 100,
        depression: 120,
    },
    {
        image: "url('../image/bellsprout.png')",
        name: 'Беллспраут',
        health: 180,
        hunger: 160,
        hygiene: 140,
        depression: 110,
    },
    {
        image: "url('../image/meowth.png')",
        name: 'Мяут',
        health: 150,
        hunger: 170,
        hygiene: 100,
        depression: 100,
    },
    {
        image: "url('../image/pidgeotto.png')",
        name: 'Пиджеотто',
        health: 200,
        hunger: 200,
        hygiene: 200,
        depression: 200,
    },
    {
        image: "url('../image/pikachu.png')",
        name: 'Пикачу',
        health: 250,
        hunger: 250,
        hygiene: 250,
        depression: 250,
    },
    {
        image: "url('../image/sandshrew.png')",
        name: 'Сэндшрю',
        health: 150,
        hunger: 160,
        hygiene: 180,
        depression: 190,
    },
    {
        image: "url('../image/slowpoke.png')",
        name: 'Слоупок',
        health: 300,
        hunger: 300,
        hygiene: 300,
        depression: 300,
    },
>>>>>>> e7e02a440bbfa57955c79237a2ff76326858058f
];